
services:
  postgres:
    image: postgres:15
    container_name: telecom_postgres
    environment:
      POSTGRES_USER: telecom_user
      POSTGRES_PASSWORD: telecom_pass
      POSTGRES_DB: telecom_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: